name: 'typescript'

on: 'push'

jobs:
  typescript:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Setup Git Project'
        uses: 'actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8' # v6.0.1

      - name: 'Setup Typescript Env'
        uses: 'actions/setup-node@v6'
        with:
          node-version: '22.x.x'

      - name: 'Install Package Manager'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.21'

      - name: 'Install Typescript Dependencies'
        run: |
          bun install
          bun install prettier --global

      - name: 'Check Git Project'
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "found dirty files"
            exit 1
          fi

      - name: 'Check Typescript Formatter'
        run: |
          prettier -c $(find ./src -name "*.ts" -o -name "*.tsx")

      - name: 'Check Typescript Linter'
        run: |
          bun run lint

      - name: 'Build Typescript Project'
        run: |
          bun run build
